export const SITE_CONFIG = {
  name: "InzuLink Rwanda",
  tagline: "Direct rentals, zero commission",
  description:
    "Rwanda's premium property rental platform connecting landlords directly with tenants. No brokers, no commissions.",
  url: "https://inzulink.rw",
  ogImage: "/images/og.jpg",
  links: {
    twitter: "https://twitter.com/inzulink",
    github: "https://github.com/inzulink",
  },
  contact: {
    email: "hello@inzulink.rw",
    phone: "+250 788 000 000",
    address: "KG 220 St, Kigali, Rwanda",
  },
} as const

export const LOCATIONS = [
  { district: "Gasabo", sectors: ["Kimironko", "Remera", "Gisozi", "Kacyiru", "Nyarutarama", "Rugando"] },
  { district: "Nyarugenge", sectors: ["Nyamirambo", "Muhima", "Kiyovu", "Gitega", "Nyarugenge"] },
  { district: "Kicukiro", sectors: ["Kicukiro", "Gahanga", "Kanombe", "Niboye", "Busanza"] },
  { district: "Musanze", sectors: ["Ruhengeri", "Muhoza", "Muko", "Cyuve", "Gacaca"] },
  { district: "Rubavu", sectors: ["Gisenyi", "Rubavu", "Bugeshi", "Cyanzarwe", "Mudende"] },
  { district: "Huye", sectors: ["Butare", "Ngoma", "Tumba", "Ruhashya", "Mukura"] },
] as const

export const PROPERTY_TYPES = [
  { value: "apartment", label: "Apartment", icon: "Building2" },
  { value: "house", label: "Family House", icon: "Home" },
  { value: "studio", label: "Studio", icon: "DoorOpen" },
  { value: "villa", label: "Luxury Villa", icon: "Warehouse" },
  { value: "shared", label: "Student Housing", icon: "GraduationCap" },
  { value: "commercial", label: "Commercial", icon: "Store" },
] as const

export const AMENITIES = [
  { value: "wifi", label: "WiFi", icon: "Wifi" },
  { value: "water", label: "Running Water", icon: "Droplets" },
  { value: "electricity", label: "Electricity", icon: "Zap" },
  { value: "parking", label: "Parking", icon: "Car" },
  { value: "furnished", label: "Furnished", icon: "Sofa" },
  { value: "security", label: "Security", icon: "Shield" },
  { value: "garden", label: "Garden", icon: "Flower2" },
  { value: "balcony", label: "Balcony", icon: "Sun" },
  { value: "gym", label: "Gym", icon: "Dumbbell" },
  { value: "pool", label: "Swimming Pool", icon: "Waves" },
  { value: "generator", label: "Generator", icon: "Battery" },
  { value: "cctv", label: "CCTV", icon: "Camera" },
] as const

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "price_asc", label: "Price: Low to High" },
  { value: "price_desc", label: "Price: High to Low" },
  { value: "popular", label: "Most Popular" },
] as const

export const STATISTICS = [
  { value: 10000, suffix: "+", label: "Verified Houses" },
  { value: 5000, suffix: "+", label: "Happy Renters" },
  { value: 2500, suffix: "+", label: "Trusted Landlords" },
  { value: 98, suffix: "%", label: "Verified Listings" },
] as const

export const FEATURED_PROPERTIES = [
  {
    id: "1",
    title: "Modern 2-Bedroom Apartment in Kimironko",
    location: "Kimironko, Gasabo",
    price: 350000,
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    type: "Apartment",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80",
    rating: 4.8,
    reviews: 24,
    isAvailable: true,
    isFeatured: true,
    isVerified: true,
    hasParking: true,
    hasInternet: true,
    landlord: "Jean-Pierre",
    landlordAvatar: "",
    aiScore: 96,
  },
  {
    id: "2",
    title: "Luxury 3-Bedroom Villa in Nyarutarama",
    location: "Nyarutarama, Gasabo",
    price: 850000,
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    type: "Villa",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    rating: 4.9,
    reviews: 18,
    isAvailable: true,
    isFeatured: true,
    isVerified: true,
    hasParking: true,
    hasInternet: true,
    landlord: "Alice",
    landlordAvatar: "",
    aiScore: 98,
  },
  {
    id: "3",
    title: "Cozy Studio Near Kacyiru Business Center",
    location: "Kacyiru, Gasabo",
    price: 180000,
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    type: "Studio",
    image: "https://images.unsplash.com/photo-1570168009544-9e7a684b1e7a?w=800&q=80",
    rating: 4.6,
    reviews: 31,
    isAvailable: true,
    isFeatured: true,
    isVerified: true,
    hasParking: false,
    hasInternet: true,
    landlord: "Patrick",
    landlordAvatar: "",
    aiScore: 92,
  },
  {
    id: "4",
    title: "Spacious 4-Bedroom Family House in Remera",
    location: "Remera, Gasabo",
    price: 600000,
    bedrooms: 4,
    bathrooms: 2,
    area: 180,
    type: "House",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    rating: 4.7,
    reviews: 15,
    isAvailable: true,
    isFeatured: false,
    isVerified: true,
    hasParking: true,
    hasInternet: true,
    landlord: "Grace",
    landlordAvatar: "",
    aiScore: 94,
  },
  {
    id: "5",
    title: "Modern 1-Bedroom Near University of Rwanda",
    location: "Nyamirambo, Nyarugenge",
    price: 120000,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    type: "Studio",
    image: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
    rating: 4.4,
    reviews: 42,
    isAvailable: true,
    isFeatured: false,
    isVerified: true,
    hasParking: false,
    hasInternet: true,
    landlord: "Emmanuel",
    landlordAvatar: "",
    aiScore: 89,
  },
  {
    id: "6",
    title: "Premium Apartment with Pool in Kicukiro",
    location: "Kicukiro, Kicukiro",
    price: 450000,
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
    type: "Apartment",
    image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
    rating: 4.8,
    reviews: 27,
    isAvailable: false,
    isFeatured: true,
    isVerified: true,
    hasParking: true,
    hasInternet: true,
    landlord: "Diane",
    landlordAvatar: "",
    aiScore: 97,
  },
  {
    id: "7",
    title: "2-Bedroom House Near Musanze Market",
    location: "Muhoza, Musanze",
    price: 200000,
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
    type: "House",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    rating: 4.5,
    reviews: 12,
    isAvailable: true,
    isFeatured: false,
    isVerified: true,
    hasParking: true,
    hasInternet: false,
    landlord: "Claude",
    landlordAvatar: "",
    aiScore: 88,
  },
  {
    id: "8",
    title: "Modern Studio with Lake View in Gisenyi",
    location: "Gisenyi, Rubavu",
    price: 150000,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    type: "Studio",
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
    rating: 4.6,
    reviews: 19,
    isAvailable: true,
    isFeatured: false,
    isVerified: true,
    hasParking: false,
    hasInternet: true,
    landlord: "Yvonne",
    landlordAvatar: "",
    aiScore: 91,
  },
  {
    id: "9",
    title: "3-Bedroom Family Home near National University",
    location: "Butare, Huye",
    price: 250000,
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    type: "House",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    rating: 4.7,
    reviews: 22,
    isAvailable: true,
    isFeatured: false,
    isVerified: true,
    hasParking: true,
    hasInternet: true,
    landlord: "David",
    landlordAvatar: "",
    aiScore: 93,
  },
  {
    id: "10",
    title: "Affordable 1-Bedroom in Nyagatare Town",
    location: "Nyagatare, Nyagatare",
    price: 100000,
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    type: "Apartment",
    image: "https://images.unsplash.com/photo-1592595896552-12b371d546d5?w=800&q=80",
    rating: 4.3,
    reviews: 8,
    isAvailable: true,
    isFeatured: false,
    isVerified: true,
    hasParking: false,
    hasInternet: false,
    landlord: "Marie",
    landlordAvatar: "",
    aiScore: 85,
  },
  {
    id: "11",
    title: "Furnished Apartment near Kacyiru Business District",
    location: "Kacyiru, Gasabo",
    price: 400000,
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    type: "Apartment",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80",
    rating: 4.9,
    reviews: 34,
    isAvailable: true,
    isFeatured: true,
    isVerified: true,
    hasParking: true,
    hasInternet: true,
    landlord: "Aimable",
    landlordAvatar: "",
    aiScore: 99,
  },
  {
    id: "12",
    title: "Penthouse Suite in Nyarutarama",
    location: "Nyarutarama, Gasabo",
    price: 1200000,
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    type: "Villa",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    rating: 5.0,
    reviews: 11,
    isAvailable: true,
    isFeatured: true,
    isVerified: true,
    hasParking: true,
    hasInternet: true,
    landlord: "Sophie",
    landlordAvatar: "",
    aiScore: 97,
  },
] as const

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Alice Mukamana",
    role: "Tenant",
    location: "Kigali",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&q=80",
    content:
      "InzuLink made finding my apartment in Kigali so easy. No broker fees, direct communication with the landlord. The process was transparent and smooth from start to finish.",
    rating: 5,
  },
  {
    id: "2",
    name: "Jean-Pierre Habimana",
    role: "Landlord",
    location: "Musanze",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&q=80",
    content:
      "I've listed 3 properties on InzuLink and found quality tenants within days. The platform saves me thousands in broker commissions every year. The AI pricing tool is incredibly accurate.",
    rating: 5,
  },
  {
    id: "3",
    name: "Grace Uwimana",
    role: "Tenant",
    location: "Kicukiro",
    avatar: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=150&q=80",
    content:
      "The AI search feature is incredible. I described exactly what I wanted and found the perfect house in hours. The property verification gave me peace of mind as a first-time renter.",
    rating: 5,
  },
  {
    id: "4",
    name: "Patrick Niyonzima",
    role: "Landlord",
    location: "Gasabo",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    content:
      "Managing my properties has never been easier. The dashboard gives me clear analytics, and the tenant screening tools help me find reliable renters quickly.",
    rating: 5,
  },
] as const

export const FAQ_ITEMS = [
  {
    question: "How does InzuLink work?",
    answer:
      "InzuLink connects tenants directly with landlords. Browse properties, contact landlords, schedule viewings, and sign leases — all without paying any broker commission."
  },
  {
    question: "Is InzuLink really free for tenants?",
    answer:
      "Yes, InzuLink is completely free for tenants. You can search, view, and contact landlords without any fees. Landlords pay a small subscription for premium features."
  },
  {
    question: "How do I verify my identity?",
    answer:
      "You can verify your identity by uploading your national ID, passport, or driver's license. We use secure encryption to protect your data."
  },
  {
    question: "What areas does InzuLink cover?",
    answer:
      "We currently cover all districts of Kigali (Gasabo, Nyarugenge, Kicukiro) and major towns including Musanze, Rubavu, Huye, Nyagatare, and Rwamagana."
  },
  {
    question: "How do I list my property?",
    answer:
      "Create a landlord account, click 'Add Property', fill in the details, upload photos and videos, and publish. Our AI helps you create an attractive listing."
  },
  {
    question: "What payment methods are accepted?",
    answer:
      "We accept Mobile Money (MTN, Airtel), bank transfers, and cards. Rent payments are processed securely through our platform."
  },
] as const

export const CATEGORIES = [
  { name: "Apartments", typeValue: "apartment", icon: "Building2", count: 850, image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=600&q=80" },
  { name: "Family Houses", typeValue: "house", icon: "Home", count: 620, image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&q=80" },
  { name: "Studios", typeValue: "studio", icon: "DoorOpen", count: 340, image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80" },
  { name: "Luxury Villas", typeValue: "villa", icon: "Warehouse", count: 180, image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80" },
  { name: "Student Housing", typeValue: "shared", icon: "GraduationCap", count: 290, image: "https://images.unsplash.com/photo-1592595896552-12b371d546d5?w=600&q=80" },
  { name: "Commercial", typeValue: "commercial", icon: "Store", count: 220, image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80" },
] as const

export const POPULAR_LOCATIONS = [
  {
    name: "Kicukiro",
    district: "Kicukiro District",
    image: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
    count: 245,
    avgRent: 280000,
    lat: -1.9663,
    lng: 30.0926,
  },
  {
    name: "Gasabo",
    district: "Gasabo District",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80",
    count: 420,
    avgRent: 350000,
    lat: -1.9441,
    lng: 30.0856,
  },
  {
    name: "Nyarugenge",
    district: "Nyarugenge District",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    count: 315,
    avgRent: 220000,
    lat: -1.9706,
    lng: 30.0578,
  },
  {
    name: "Musanze",
    district: "Musanze District",
    image: "https://images.unsplash.com/photo-1570168009544-9e7a684b1e7a?w=800&q=80",
    count: 156,
    avgRent: 180000,
    lat: -1.4998,
    lng: 29.6350,
  },
  {
    name: "Rubavu",
    district: "Rubavu District",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    count: 134,
    avgRent: 160000,
    lat: -1.6781,
    lng: 29.2587,
  },
  {
    name: "Huye",
    district: "Huye District",
    image: "https://images.unsplash.com/photo-1592595896616-c37162298647?w=800&q=80",
    count: 112,
    avgRent: 140000,
    lat: -2.6030,
    lng: 29.7423,
  },
] as const

export const BEDROOM_OPTIONS = [
  { value: "1", label: "1 Bed" },
  { value: "2", label: "2 Beds" },
  { value: "3", label: "3 Beds" },
  { value: "4", label: "4 Beds" },
  { value: "5", label: "5+ Beds" },
] as const

export const BATHROOM_OPTIONS = [
  { value: "1", label: "1 Bath" },
  { value: "2", label: "2 Baths" },
  { value: "3", label: "3 Baths" },
  { value: "4", label: "4+ Baths" },
] as const

export const WHY_CHOOSE_US = [
  {
    title: "No Broker Commission",
    description: "Connect directly with landlords and save up to 30% on rental costs. No middlemen, no hidden fees.",
    icon: "Banknote",
  },
  {
    title: "Verified Properties",
    description: "Every listing is manually verified for authenticity. We inspect properties before they go live.",
    icon: "ShieldCheck",
  },
  {
    title: "AI-Powered Search",
    description: "Find your perfect home in seconds. Describe what you want and our AI finds the best matches.",
    icon: "Sparkles",
  },
  {
    title: "Trusted Landlords",
    description: "All landlords undergo identity verification. Rent with confidence from verified property owners.",
    icon: "Users",
  },
] as const
