import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const landlords = [
  { email: "jean@inzulink.rw", name: "Jean-Pierre", phone: "+250788000001", role: "LANDLORD" as const },
  { email: "alice@inzulink.rw", name: "Alice", phone: "+250788000002", role: "LANDLORD" as const },
  { email: "patrick@inzulink.rw", name: "Patrick", phone: "+250788000003", role: "LANDLORD" as const },
  { email: "grace@inzulink.rw", name: "Grace", phone: "+250788000004", role: "LANDLORD" as const },
  { email: "emmanuel@inzulink.rw", name: "Emmanuel", phone: "+250788000005", role: "LANDLORD" as const },
  { email: "diane@inzulink.rw", name: "Diane", phone: "+250788000006", role: "LANDLORD" as const },
  { email: "claude@inzulink.rw", name: "Claude", phone: "+250788000007", role: "LANDLORD" as const },
  { email: "yvonne@inzulink.rw", name: "Yvonne", phone: "+250788000008", role: "LANDLORD" as const },
  { email: "david@inzulink.rw", name: "David", phone: "+250788000009", role: "LANDLORD" as const },
  { email: "marie@inzulink.rw", name: "Marie", phone: "+250788000010", role: "LANDLORD" as const },
  { email: "aimable@inzulink.rw", name: "Aimable", phone: "+250788000011", role: "LANDLORD" as const },
  { email: "sophie@inzulink.rw", name: "Sophie", phone: "+250788000012", role: "LANDLORD" as const },
]

const properties = [
  {
    title: "Modern 2-Bedroom Apartment in Kimironko",
    description: "A well-maintained 2-bedroom apartment in the heart of Kimironko. Close to supermarkets, schools, and public transport. Features modern finishes, tiled floors, and ample natural light.",
    price: 350000,
    type: "APARTMENT" as const,
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    district: "Gasabo",
    sector: "Kimironko",
    furnished: true,
    familyFriendly: true,
    featured: true,
    verified: true,
    hasParking: true,
    hasInternet: true,
    landlordEmail: "jean@inzulink.rw",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80",
    rating: 4.8,
    reviews: 24,
    aiScore: 96,
  },
  {
    title: "Luxury 3-Bedroom Villa in Nyarutarama",
    description: "Beautiful 3-bedroom villa in the prestigious Nyarutarama neighborhood. Large compound with garden, two parking spots, and modern interiors. Ideal for families or professionals.",
    price: 850000,
    type: "VILLA" as const,
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    district: "Gasabo",
    sector: "Nyarutarama",
    furnished: true,
    familyFriendly: true,
    featured: true,
    verified: true,
    hasParking: true,
    hasInternet: true,
    landlordEmail: "alice@inzulink.rw",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    rating: 4.9,
    reviews: 18,
    aiScore: 98,
  },
  {
    title: "Cozy Studio Near Kacyiru Business Center",
    description: "Affordable studio apartment in Kacyiru, walking distance to business centers and restaurants. Perfect for young professionals. Includes WiFi and water.",
    price: 180000,
    type: "STUDIO" as const,
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    district: "Gasabo",
    sector: "Kacyiru",
    furnished: false,
    familyFriendly: false,
    featured: true,
    verified: true,
    hasParking: false,
    hasInternet: true,
    landlordEmail: "patrick@inzulink.rw",
    image: "https://images.unsplash.com/photo-1570168009544-9e7a684b1e7a?w=800&q=80",
    rating: 4.6,
    reviews: 31,
    aiScore: 92,
  },
  {
    title: "Spacious 4-Bedroom Family House in Remera",
    description: "Large family house in Remera with a beautiful garden, modern kitchen, and plenty of space. Close to top schools and the MTN center.",
    price: 600000,
    type: "HOUSE" as const,
    bedrooms: 4,
    bathrooms: 2,
    area: 180,
    district: "Gasabo",
    sector: "Remera",
    furnished: false,
    familyFriendly: true,
    featured: false,
    verified: true,
    hasParking: true,
    hasInternet: true,
    landlordEmail: "grace@inzulink.rw",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    rating: 4.7,
    reviews: 15,
    aiScore: 94,
  },
  {
    title: "Modern 1-Bedroom Near University of Rwanda",
    description: "Conveniently located 1-bedroom near the University of Rwanda in Nyamirambo. Ideal for students. Walking distance to campus and local markets.",
    price: 120000,
    type: "STUDIO" as const,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    district: "Nyarugenge",
    sector: "Nyamirambo",
    furnished: false,
    familyFriendly: false,
    studentFriendly: true,
    featured: false,
    verified: true,
    hasParking: false,
    hasInternet: true,
    landlordEmail: "emmanuel@inzulink.rw",
    image: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
    rating: 4.4,
    reviews: 42,
    aiScore: 89,
  },
  {
    title: "Premium Apartment with Pool in Kicukiro",
    description: "High-end apartment complex in Kicukiro with swimming pool, gym, and 24-hour security. Two bedrooms with modern finishes and balcony.",
    price: 450000,
    type: "APARTMENT" as const,
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
    district: "Kicukiro",
    sector: "Kicukiro",
    furnished: true,
    familyFriendly: true,
    featured: true,
    verified: true,
    hasParking: true,
    hasInternet: true,
    landlordEmail: "diane@inzulink.rw",
    image: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
    rating: 4.8,
    reviews: 27,
    aiScore: 97,
  },
  {
    title: "2-Bedroom House Near Musanze Market",
    description: "Cozy 2-bedroom house near the main market in Musanze. Walking distance to town center, bus park, and restaurants. Ideal for a small family.",
    price: 200000,
    type: "HOUSE" as const,
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
    district: "Musanze",
    sector: "Muhoza",
    furnished: false,
    familyFriendly: true,
    featured: false,
    verified: true,
    hasParking: true,
    hasInternet: false,
    landlordEmail: "claude@inzulink.rw",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    rating: 4.5,
    reviews: 12,
    aiScore: 88,
  },
  {
    title: "Modern Studio with Lake View in Gisenyi",
    description: "Beautiful studio apartment overlooking Lake Kivu in Gisenyi town. Short walk to the beach, restaurants, and the border. Fully furnished.",
    price: 150000,
    type: "STUDIO" as const,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    district: "Rubavu",
    sector: "Gisenyi",
    furnished: true,
    familyFriendly: false,
    featured: false,
    verified: true,
    hasParking: false,
    hasInternet: true,
    landlordEmail: "yvonne@inzulink.rw",
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
    rating: 4.6,
    reviews: 19,
    aiScore: 91,
  },
  {
    title: "3-Bedroom Family Home near National University",
    description: "Spacious family home in Butare near the National University of Rwanda. Three bedrooms, large living room, and a beautiful garden. Quiet neighborhood.",
    price: 250000,
    type: "HOUSE" as const,
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    district: "Huye",
    sector: "Butare",
    furnished: false,
    familyFriendly: true,
    featured: false,
    verified: true,
    hasParking: true,
    hasInternet: true,
    landlordEmail: "david@inzulink.rw",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    rating: 4.7,
    reviews: 22,
    aiScore: 93,
  },
  {
    title: "Affordable 1-Bedroom in Nyagatare Town",
    description: "Budget-friendly 1-bedroom unit in the growing town of Nyagatare. Perfect for teachers and civil servants. Walking distance to local amenities.",
    price: 100000,
    type: "APARTMENT" as const,
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    district: "Nyagatare",
    sector: "Nyagatare",
    furnished: false,
    familyFriendly: false,
    featured: false,
    verified: true,
    hasParking: false,
    hasInternet: false,
    landlordEmail: "marie@inzulink.rw",
    image: "https://images.unsplash.com/photo-1592595896552-12b371d546d5?w=800&q=80",
    rating: 4.3,
    reviews: 8,
    aiScore: 85,
  },
  {
    title: "Furnished Apartment near Kacyiru Business District",
    description: "Fully furnished 2-bedroom apartment in Kacyiru, minutes from the business district. Modern furniture, fast internet, and parking included. Move-in ready.",
    price: 400000,
    type: "APARTMENT" as const,
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    district: "Gasabo",
    sector: "Kacyiru",
    furnished: true,
    familyFriendly: true,
    featured: true,
    verified: true,
    hasParking: true,
    hasInternet: true,
    landlordEmail: "aimable@inzulink.rw",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80",
    rating: 4.9,
    reviews: 34,
    aiScore: 99,
  },
  {
    title: "Penthouse Suite in Nyarutarama",
    description: "Executive penthouse in Nyarutarama with panoramic views of Kigali. Four bedrooms, three bathrooms, private terrace, and premium finishes throughout.",
    price: 1200000,
    type: "VILLA" as const,
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    district: "Gasabo",
    sector: "Nyarutarama",
    furnished: true,
    familyFriendly: true,
    featured: true,
    verified: true,
    hasParking: true,
    hasInternet: true,
    landlordEmail: "sophie@inzulink.rw",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    rating: 5.0,
    reviews: 11,
    aiScore: 97,
  },
]

const testimonials = [
  {
    name: "Alice Mukamana",
    role: "Tenant",
    location: "Kigali",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&q=80",
    content: "InzuLink made finding my apartment in Kigali so easy. No broker fees, direct communication with the landlord. The process was transparent and smooth from start to finish.",
    rating: 5,
    propertyTitle: "Modern 2-Bedroom Apartment in Kimironko",
  },
  {
    name: "Jean-Pierre Habimana",
    role: "Landlord",
    location: "Musanze",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&q=80",
    content: "I've listed 3 properties on InzuLink and found quality tenants within days. The platform saves me thousands in broker commissions every year.",
    rating: 5,
    propertyTitle: "2-Bedroom House Near Musanze Market",
  },
  {
    name: "Grace Uwimana",
    role: "Tenant",
    location: "Kicukiro",
    avatar: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=150&q=80",
    content: "The AI search feature is incredible. I described exactly what I wanted and found the perfect house in hours. The property verification gave me peace of mind.",
    rating: 5,
    propertyTitle: "Premium Apartment with Pool in Kicukiro",
  },
  {
    name: "Patrick Niyonzima",
    role: "Landlord",
    location: "Gasabo",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    content: "Managing my properties has never been easier. The dashboard gives me clear analytics, and the tenant screening tools help me find reliable renters quickly.",
    rating: 5,
    propertyTitle: "Modern 2-Bedroom Apartment in Kimironko",
  },
]

async function main() {
  console.log("Seeding database...")

  for (const l of landlords) {
    await prisma.user.upsert({
      where: { email: l.email },
      update: {},
      create: {
        email: l.email,
        name: l.name,
        phone: l.phone,
        role: l.role,
        verified: true,
      },
    })
  }
  console.log(`Created ${landlords.length} users`)

  for (const p of properties) {
    const landlord = await prisma.user.findUnique({ where: { email: p.landlordEmail } })
    if (!landlord) continue

    await prisma.property.create({
      data: {
        title: p.title,
        description: p.description,
        price: p.price,
        type: p.type,
        bedrooms: p.bedrooms,
        bathrooms: p.bathrooms,
        area: p.area,
        district: p.district,
        sector: p.sector,
        furnished: p.furnished,
        familyFriendly: p.familyFriendly,
        studentFriendly: "studentFriendly" in p ? (p as any).studentFriendly : false,
        featured: p.featured,
        verified: p.verified,
        aiScore: p.aiScore,
        images: [p.image],
        amenities: [
          ...(p.hasInternet ? ["wifi"] : []),
          ...(p.hasParking ? ["parking"] : []),
          "water",
          "electricity",
        ],
        landlordId: landlord.id,
      },
    })
  }
  console.log(`Created ${properties.length} properties`)

  const allProperties = await prisma.property.findMany({ include: { landlord: true } })

  for (const t of testimonials) {
    const property = allProperties.find((p) => p.title === t.propertyTitle)
    if (!property) continue

    const tenant = await prisma.user.findFirst({
      where: { email: { not: property.landlord.email } },
    })
    if (!tenant) continue

    await prisma.review.create({
      data: {
        rating: t.rating,
        content: t.content,
        userId: tenant.id,
        propertyId: property.id,
      },
    })
  }
  console.log(`Created ${testimonials.length} reviews`)

  console.log("Seeding complete!")
}

main()
  .catch((e) => {
    console.error("Seed error:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
